port: &port 3000

container:
  image: quiz-api
  port: *port
  resourceTier: M

configMap:
  environment: production
  redisHost: services.lynxmagnus.com

secret:
  secretsPath: /aircraft-cache

deployment: {}

ingress:
  host: example.com

readinessProbe:
  httpGet:
    path: /healthz
    port: *port

livenessProbe:
  httpGet:
    path: /healthz
    port: *port

startupProbe:
  httpGet:
    path: /healthz
    port: *port
  initialDelaySeconds: 10
