{{- include "helm-library.configmap" (list . "quiz-api.configmap") -}}
{{- define "quiz-api.configmap" -}}
data:
  PORT: {{ .Values.container.port | quote }}
  NODE_ENV: {{ .Values.configMap.environment | quote }}
  REDIS_HOST: {{ .Values.configMap.redisHost | quote }}
{{- end -}}
